#!/bin/bash --login
#$ -cwd
#$ -l nvidia_v100            # Can instead use 'nvidia_a100' for the A100 GPUs (if permitted!)
run_command() {
    local data=$1
    local model=$2

    # Default model is tgn-attn
    if [[ -z $model ]]; then
        model="tgn-attn"
    fi

    # Check dataset choice
    if [[ $data == "wiki" ]]; then
        data="wikipedia"
    elif [[ $data == "reddit" ]]; then
        data="reddit"
    elif [[ $data == "social" ]]; then
        data="socialevolve_2weeks"
    elif [[ $data == "wiki_fm" || $data == "wikipedia_fm" ]]; then
        data="wikipedia_fm"
    elif [[ $data == "reddit_fm" ]]; then
        data="reddit_fm"
    fi

    # Run appropriate python script based on model choice
    if [[ $model == "tgn-attn" ]]; then
        python train_self_supervised.py -d $data --use_memory --n_runs 1 --prefix $model-$data
        python train_supervised.py -d $data --use_memory --prefix $model-$data --n_runs 3
    elif [[ $model == "jodie" ]]; then
        python train_self_supervised.py -d $data --use_memory --memory_updater rnn --embedding_module time --prefix $model-$data --n_runs 1
        python train_supervised.py -d $data --use_memory --memory_updater rnn --embedding_module time --prefix $model-$data --n_runs 3
    elif [[ $model == "dyrep" ]]; then
        python train_self_supervised.py -d $data --use_memory --memory_updater rnn --dyrep --use_destination_embedding_in_message --prefix $model-$data --n_runs 1
        python train_supervised.py -d $data --use_memory --memory_updater rnn --dyrep --use_destination_embedding_in_message --prefix $model-$data --n_runs 3
    fi
}

module load libs/cuda/11.7.0
conda activate twgsl
# Copy a directory of files from scratch to the GPU node's local NVMe storage
cp -r ~/scratch/tgn/ $TMPDIR

# Process the data with a GPU app, from within the local NVMe storage area
cd $TMPDIR/tgn/
run_command $1 $2

# Copy the results back to the main scratch area
rsync -av --progress \
    --exclude 'jobscript.e*' \
    --exclude 'jobscript.o*' \
    "$TMPDIR/tgn/" ~/scratch/tgn/

# The batch system will automatically delete the contents of $TMPDIR at the end of your job.
# cd ~/scratch/tgn/
# git pull
# git add ./log/
# git commit -m "logs updated"
# git push

# sleep 3
#$ -m ea
#$ -M jiafeng.xiong@manchester.ac.uk     # Send email when finished.